"""Pack → Cedar policies for the Microsoft Agent Governance Toolkit (and AVP).

Entity model (documented in the emitted header):
    principal  Agent::"<user>"      attrs: roles (Set<String>), plus JWT claims
    action     Action::"<target>.<tool>"
    resource   Tool::"<target>.<tool>"
    context    { args: {...}, grant: Bool }

Cedar can see ``context.args`` so argument rules compile natively. Holds still
need state: a rule with ``hold_if`` compiles to ``permit ... when { context.grant }``
for the post-approval retry plus the unconditional allow branch; the PDS
(RegentGuard) decides the hold itself. ``forbid`` always wins in Cedar, which
matches Regent's deny-before-hold-before-allow order exactly.
"""
from __future__ import annotations

from regent.compilers.translate import Dialect, Uncompilable, translate
from regent.core.models import Pack, Rule
from regent.core.ports import CompiledPolicy


def _cedar_ref(p: str) -> str:
    return "principal" if p == "user" else f"principal.{p}"


CEDAR = Dialect(
    name="cedar",
    args_ref=lambda a: f"context.args.{a}",
    principal_ref=_cedar_ref,
    in_=lambda a, b: f"{b}.contains({a})" if b.startswith("[") or b.startswith("principal") or b.startswith("context")
    else f"{a} in {b}",
    not_in=lambda a, b: f"!({b}.contains({a}))",
    functions={
        "startswith": lambda a: a[0] + " like " + a[1][:-1] + '*"',
        "any_in": lambda a: f"{a[0]}.containsAny({a[1]})",
    },
    has=lambda ref: f"{ref.rsplit('.', 1)[0]} has {ref.rsplit('.', 1)[1]}" if "." in ref else "true",
)


def _action(tool: str) -> str:
    if tool == "*":
        return "true"
    return f'action == Action::"{tool}"'


def compile_rule(r: Rule, firm: dict | None = None) -> tuple[list[str], bool, str | None]:
    if "*" in r.tool and r.tool != "*":
        # Cedar has no glob on entity ids; group tools under an Action group in the entity store instead.
        return ([f'// {r.id}: glob tool "{r.tool}" — model as an Action group ActionGroup::"{r.tool}" in the entity store; PDS enforces meanwhile'],
                False, "glob tool pattern needs an Action group")
    out: list[str] = []
    act = _action(r.tool)
    try:
        if r.deny_if:
            out.append(f'@id("{r.id}-deny")\nforbid(principal, action, resource) when {{ {act} && ({translate(r.deny_if, CEDAR, firm)}) }};')
        if r.hold_if:
            hold = translate(r.hold_if, CEDAR, firm)
            out.append(f'@id("{r.id}-hold")\n// hold: Regent PDS opens an approval; after approval the retry carries context.grant == true\n'
                       f'permit(principal, action, resource) when {{ {act} && ({hold}) && context.grant == true }};')
            if r.allow_if:
                out.append(f'@id("{r.id}-allow")\npermit(principal, action, resource) when {{ {act} && !({hold}) && ({translate(r.allow_if, CEDAR, firm)}) }};')
            else:
                out.append(f'@id("{r.id}-allow")\npermit(principal, action, resource) when {{ {act} && !({hold}) }};')
        elif r.allow_if:
            out.append(f'@id("{r.id}-allow")\npermit(principal, action, resource) when {{ {act} && ({translate(r.allow_if, CEDAR, firm)}) }};')
    except Uncompilable as e:
        return ([f"// {r.id}: not compilable to Cedar ({e}); PDS enforces"], False, str(e))
    return out, not bool(r.hold_if), ("hold needs PDS state" if r.hold_if else None)


class CedarCompiler:
    dialect = "cedar"

    def compile(self, packs: list[Pack]) -> CompiledPolicy:
        lines = ["// Generated by `regent compile --dialect cedar` from "
                 + ", ".join(f"{p.name}@{(p.source_hash or '')[:12]}" for p in packs),
                 "// Entities: principal Agent::<user> {roles: Set<String>, ...claims}; action Action::<target.tool>;",
                 "// context {args: Record, grant: Bool}. forbid wins, matching Regent's deny > hold > allow order.", ""]
        native, pds, notes = [], [], []
        for p in packs:
            for r in p.rules:
                body, is_native, note = compile_rule(r, p.firm)
                lines.append(f"// {r.id} · controls: {', '.join(r.controls)} · examiner asks: {r.examiner_asks}")
                lines.extend(body)
                lines.append("")
                (native if is_native else pds).append(r.id)
                if note:
                    notes.append(f"{r.id}: {note}")
        return CompiledPolicy("cedar", "\n".join(lines), native, pds, notes)
