"""Pack → Rego (OPA) for AGT's OPA backend or any OPA sidecar.

Input document:
    input.tool        "custodian.place_trade"
    input.args        {...}
    input.principal   {user, agent, roles: [...], ...claims}
    input.grant       true when the retry carries a valid Regent grant

Output: data.regent.decision ∈ {"deny","hold","allow"} plus data.regent.rule.
"""
from __future__ import annotations


from regent.compilers.translate import Dialect, Uncompilable, translate
from regent.core.match import compile_expression
from regent.core.models import Pack
from regent.core.ports import CompiledPolicy

REGO = Dialect(
    name="rego",
    args_ref=lambda a: f"input.args.{a}",
    principal_ref=lambda p: f"input.principal.{p}",
    in_=lambda a, b: f"{a} in {b}",
    not_in=lambda a, b: f"not {a} in {b}",
    and_="\n\t",
    or_=None,
    paren_and=False,  # handled by splitting into multiple bodies below (Rego has no inline OR)
    not_=lambda x: f"not ({x})",
    functions={
        "len": lambda a: f"count({a[0]})",
        "lower": lambda a: f"lower({a[0]})",
        "upper": lambda a: f"upper({a[0]})",
        "startswith": lambda a: f"startswith({a[0]}, {a[1]})",
        "endswith": lambda a: f"endswith({a[0]}, {a[1]})",
        "matches": lambda a: f"regex.match({a[1]}, {a[0]})",
        "contains_pii": lambda a: f"regent_pii({a[0]}, {a[1] if len(a) > 1 else '[]'})",
    },
    has=lambda ref: f"{ref}",
)


def _conds(expr: str, firm: dict | None = None) -> list[str]:
    """Rego bodies are conjunctions. A top-level ``or`` becomes one body per
    operand (Rego's incremental rule definitions); nested ``or`` is uncompilable."""
    import ast as _ast
    from regent.compilers.translate import _tr
    tree = compile_expression(expr).tree
    if isinstance(tree, _ast.BoolOp) and isinstance(tree.op, _ast.Or):
        return [_tr(v, REGO, firm) for v in tree.values]
    return [translate(expr, REGO, firm)]


def _bodies(head: str, tool_cond: str, expr: str, extra: list[str] | None = None, negate: bool = False,
            firm: dict | None = None) -> list[str]:
    out: list[str] = []
    conds = _conds(expr, firm)
    if negate:
        # not (A or B) == not A and not B  → one body; not (A and B) → keep as a single negated expr
        neg = [f"not ({c})" for c in conds] if len(conds) > 1 else [f"not ({translate(expr, REGO, firm)})"]
        out += [f"{head} if {{", f"\t{tool_cond}", *[f"\t{c}" for c in neg], *[f"\t{e}" for e in (extra or [])], "}", ""]
        return out
    for c in conds:
        out += [f"{head} if {{", f"\t{tool_cond}", f"\t{c}", *[f"\t{e}" for e in (extra or [])], "}", ""]
    return out


def _tool_cond(tool: str) -> str:
    if tool == "*":
        return "true"
    if "*" in tool:
        return f'glob.match("{tool}", ["."], input.tool)'
    return f'input.tool == "{tool}"'


class RegoCompiler:
    dialect = "rego"

    def compile(self, packs: list[Pack]) -> CompiledPolicy:
        L = ["# Generated by `regent compile --dialect rego` from "
             + ", ".join(f"{p.name}@{(p.source_hash or '')[:12]}" for p in packs),
             "package regent", "", "import rego.v1", "", "default decision := \"deny\"", "",
             "regent_pii(text, kinds) if {", "\tsome k in kinds",
             "\tpatterns := {\"ssn\": `\\b\\d{3}-?\\d{2}-?\\d{4}\\b`, \"account_number\": `(?i)\\b(acct|account)[\\s#:]*\\d{6,17}\\b`, \"credit_card\": `\\b(\\d[ -]?){13,19}\\b`}",
             "\tregex.match(patterns[k], text)", "}", ""]
        native, pds, notes = [], [], []
        for p in packs:
            for r in p.rules:
                L.append(f"# {r.id} · controls: {', '.join(r.controls)} · examiner asks: {r.examiner_asks}")
                try:
                    tc = _tool_cond(r.tool)
                    if r.deny_if:
                        L += _bodies(f'deny["{r.id}"]', tc, r.deny_if, firm=p.firm)
                    if r.hold_if:
                        L += _bodies(f'hold["{r.id}"]', tc, r.hold_if, ["not input.grant == true"], firm=p.firm)
                        L += _bodies(f'allow["{r.id}"]', tc, r.hold_if, ["input.grant == true"], firm=p.firm)
                    if r.allow_if:
                        L += _bodies(f'allow["{r.id}"]', tc, r.allow_if, firm=p.firm)
                    elif r.hold_if:
                        L += _bodies(f'allow["{r.id}"]', tc, r.hold_if, negate=True, firm=p.firm)
                    (pds if r.hold_if else native).append(r.id)
                    if r.hold_if:
                        notes.append(f"{r.id}: hold needs PDS state (grant); Rego expresses the retry only")
                except Uncompilable as e:
                    L += [f"# {r.id}: not compilable ({e}); PDS enforces", ""]
                    pds.append(r.id)
                    notes.append(f"{r.id}: {e}")
        L += ["decision := \"deny\" if { count(deny) > 0 }",
              "decision := \"hold\" if { count(deny) == 0; count(hold) > 0 }",
              "decision := \"allow\" if { count(deny) == 0; count(hold) == 0; count(allow) > 0 }", "",
              "rule := r if { some r in deny }", "rule := r if { count(deny) == 0; some r in hold }",
              "rule := r if { count(deny) == 0; count(hold) == 0; some r in allow }", ""]
        return CompiledPolicy("rego", "\n".join(L), native, pds, notes)
