# Generated by `regent compile --dialect rego` from ria/v1@b51f20b38e84
package regent

import rego.v1

default decision := "deny"

regent_pii(text, kinds) if {
	some k in kinds
	patterns := {"ssn": `\b\d{3}-?\d{2}-?\d{4}\b`, "account_number": `(?i)\b(acct|account)[\s#:]*\d{6,17}\b`, "credit_card": `\b(\d[ -]?){13,19}\b`}
	regex.match(patterns[k], text)
}

# RIA-TRD-011 · controls: FIDUCIARY-2019-INTERP, SEC-206(4)-7, SEC-204-2(a)(3) · examiner asks: How does the firm ensure agent-initiated orders are placed only in accounts where it holds discretionary authority or has a documented client instruction?
deny["RIA-TRD-011"] if {
	input.tool == "custodian.place_trade"
	not (input.args.discretionary)
	not (input.args.client_instruction_id)
}

# RIA-TRD-002 · controls: SEC-206(3), SEC-206(3)-2, SEC-204-2(a)(7) · examiner asks: How do you prevent principal or agency-cross trades from being executed without the consent and confirmation records the rule requires?
deny["RIA-TRD-002"] if {
	input.tool == "custodian.place_trade"
	input.args.capacity == "principal"
	not (input.args.client_consent_id)
}

deny["RIA-TRD-002"] if {
	input.tool == "custodian.place_trade"
	input.args.capacity == "agency_cross"
	not (input.args.cross_confirmation_id)
}

# RIA-ETH-003 · controls: SEC-204A-1, SEC-206(4)-7 · examiner asks: Can the client-trading agent transact in access-person or proprietary accounts, and how are those trades pre-cleared and reported under the Code of Ethics?
deny["RIA-ETH-003"] if {
	input.tool == "custodian.place_trade"
	input.args.account_type in ["employee", "access_person", "proprietary"]
}

# RIA-TRD-012 · controls: SEC-206(4)-7, FIDUCIARY-2019-INTERP · examiner asks: How do you prevent options or margin transactions in accounts the client has not been approved for?
deny["RIA-TRD-012"] if {
	input.tool == "custodian.place_trade"
	input.args.security_type in ["option", "options", "margin"]
	not (input.args.account_options_approved)
}

# RIA-REC-019 · controls: SEC-204-2(a)(3), SEC-204-2(e) · examiner asks: Produce the order memorandum for each agent-initiated order, showing who recommended, who placed, the executing broker and whether the order was discretionary.
deny["RIA-REC-019"] if {
	input.tool == "custodian.place_trade"
	not (input.args.discretionary
	input.args.recommended_by
	input.args.placed_by
	input.args.executing_broker
	input.args.order_terms)
}

# RIA-TRD-001 · controls: SEC-206(4)-7, SEC-204-2(a)(3), SEC-204A, FIDUCIARY-2019-INTERP · examiner asks: How are agent-initiated orders supervised for mandate, restricted-list and concentration exceptions, and where is the record of each exception review?
# RIA-TRD-001: not compilable (rego: 'or' has no inline form — split the rule); PDS enforces

# RIA-FEE-020 · controls: SEC-206(4)-2, SEC-206(4)-7, SEC-204-2(a)(2) · examiner asks: How are advisory fees calculated and reconciled to client agreements before being deducted, and who reviews exceptions?
# RIA-FEE-020: not compilable (rego: function abs() has no native equivalent); PDS enforces

# RIA-CUS-004 · controls: SEC-206(4)-2, IAA-SLOA-NAL-2017 · examiner asks: For each third-party transfer an agent initiated, show the standing letter of authorization and that all seven no-action conditions were met — or the surprise examination that covers it.
# RIA-CUS-004: not compilable (rego: 'or' has no inline form — split the rule); PDS enforces

# RIA-CUS-015 · controls: SEC-RegS-ID-248.201, SEC-206(4)-2, SEC-204-2(a)(7) · examiner asks: What is your red-flags procedure for transfers where the payee or instructions changed recently, and how is call-back verification evidenced?
hold["RIA-CUS-015"] if {
	input.tool == "custodian.transfer_funds"
	input.args.instructions_changed_days_ago
	input.args.instructions_changed_days_ago <= 30
	not input.grant == true
}

allow["RIA-CUS-015"] if {
	input.tool == "custodian.transfer_funds"
	input.args.instructions_changed_days_ago
	input.args.instructions_changed_days_ago <= 30
	input.grant == true
}

allow["RIA-CUS-015"] if {
	input.tool == "custodian.transfer_funds"
	not (input.args.instructions_changed_days_ago
	input.args.instructions_changed_days_ago <= 30)
}

# RIA-CUS-016 · controls: SEC-206(4)-2, IAA-SLOA-NAL-2017, SEC-RegS-ID-248.201 · examiner asks: How does the firm ensure each third-party disbursement stays within the SLOA no-action conditions, and who attests to that per transfer?
hold["RIA-CUS-016"] if {
	input.tool == "custodian.transfer_funds"
	input.args.destination_type == "third_party"
	not input.grant == true
}

allow["RIA-CUS-016"] if {
	input.tool == "custodian.transfer_funds"
	input.args.destination_type == "third_party"
	input.grant == true
}

allow["RIA-CUS-016"] if {
	input.tool == "custodian.transfer_funds"
	not (input.args.destination_type == "third_party")
}

# RIA-CUS-017 · controls: SEC-206(4)-2, SEC-204-2(a)(7) · examiner asks: How are first-party wires to outside institutions matched to the client's written authorization?
hold["RIA-CUS-017"] if {
	input.tool == "custodian.transfer_funds"
	input.args.destination_type == "first_party"
	input.args.transfer_type == "wire"
	not input.grant == true
}

allow["RIA-CUS-017"] if {
	input.tool == "custodian.transfer_funds"
	input.args.destination_type == "first_party"
	input.args.transfer_type == "wire"
	input.grant == true
}

allow["RIA-CUS-017"] if {
	input.tool == "custodian.transfer_funds"
	not (input.args.destination_type == "first_party"
	input.args.transfer_type == "wire")
}

# RIA-CUS-018 · controls: SEC-206(4)-2, IAA-SLOA-NAL-2017 · examiner asks: Which agent-initiated money movements does the firm treat as custody-free, and on what basis?
allow["RIA-CUS-018"] if {
	input.tool == "custodian.transfer_funds"
	input.args.destination_type == "first_party"
	input.args.transfer_type in ["journal", "ach"]
	input.args.like_titled
}

# RIA-DAT-005 · controls: SEC-RegS-P-248.30, GLBA-501(b) · examiner asks: What prevents Social Security numbers from leaving the firm through automated channels, and can anyone override it?
deny["RIA-DAT-005"] if {
	input.tool == "email.send"
	regent_pii(input.args.body, ["ssn"])
}

deny["RIA-DAT-005"] if {
	input.tool == "email.send"
	regent_pii(input.args.subject, ["ssn"])
}

# RIA-DAT-014 · controls: SEC-RegS-P-248.30(a)(2), GLBA-501(b) · examiner asks: Under what conditions may nonpublic personal information be sent by automated email, and how is the recipient verified against the account's email of record?
deny["RIA-DAT-014"] if {
	input.tool == "email.send"
	regent_pii(input.args.body, ["account_number", "dob", "routing_number", "credit_card"])
	not (input.args.recipient_is_email_of_record
	input.args.channel in ["portal", "encrypted_email"])
}

# RIA-COM-013 · controls: SEC-204-2(a)(7), SEC-204-2(e) · examiner asks: Are all agent-sent communications captured in the firm's books-and-records archive, and how would an unarchived message be prevented?
deny["RIA-COM-013"] if {
	input.tool == "email.send"
	not (input.args.archived)
}

# RIA-COM-006 · controls: SEC-206(4)-1, SEC-204-2(a)(11), SEC-204-2(a)(7) · examiner asks: How does the firm identify which agent-drafted communications are advertisements under Rule 206(4)-1, and how are those reviewed and retained?
# RIA-COM-006: not compilable (rego: 'or' has no inline form — split the rule); PDS enforces

# RIA-DAT-007 · controls: SEC-RegS-P-248.30, SEC-RegS-P-248.30(a)(5), GLBA-501(b) · examiner asks: Who authorised each bulk export of client data by automated systems, to which service provider, and how many records?
hold["RIA-DAT-007"] if {
	input.tool == "crm.export"
	true
	not input.grant == true
}

allow["RIA-DAT-007"] if {
	input.tool == "crm.export"
	true
	input.grant == true
}

allow["RIA-DAT-007"] if {
	input.tool == "crm.export"
	not (true)
}

# RIA-REC-008 · controls: SEC-204-2(a)(10), SEC-204-3, SEC-204-2(a)(14), SEC-206(4)-7 · examiner asks: How do you ensure agents send only approved client agreements with the brochure delivered, and where are executed copies and delivery records retained?
hold["RIA-REC-008"] if {
	input.tool == "esign.send_envelope"
	not (input.args.template_id in input.principal.approved_templates)
	not input.grant == true
}

hold["RIA-REC-008"] if {
	input.tool == "esign.send_envelope"
	not (input.args.adv_delivery_receipt_id)
	not input.grant == true
}

allow["RIA-REC-008"] if {
	input.tool == "esign.send_envelope"
	not (input.args.template_id in input.principal.approved_templates)
	input.grant == true
}

allow["RIA-REC-008"] if {
	input.tool == "esign.send_envelope"
	not (input.args.adv_delivery_receipt_id)
	input.grant == true
}

allow["RIA-REC-008"] if {
	input.tool == "esign.send_envelope"
	input.args.template_id in input.principal.approved_templates
	input.args.adv_delivery_receipt_id
}

# RIA-REC-009 · controls: SEC-204-2(e) · examiner asks: Can an automated agent delete or alter required records, and how would you know?
deny["RIA-REC-009"] if {
	glob.match("*.delete*", ["."], input.tool)
	true
}

# RIA-REC-010 · controls: SEC-204-2(e), SEC-204-2(a)(10) · examiner asks: Can an automated agent void executed or in-flight client agreements?
deny["RIA-REC-010"] if {
	input.tool == "esign.void_envelope"
	input.args.envelope_status in ["sent", "delivered", "completed"]
}

allow["RIA-REC-010"] if {
	input.tool == "esign.void_envelope"
	input.args.envelope_status in ["draft", "created"]
}

decision := "deny" if { count(deny) > 0 }
decision := "hold" if { count(deny) == 0; count(hold) > 0 }
decision := "allow" if { count(deny) == 0; count(hold) == 0; count(allow) > 0 }

rule := r if { some r in deny }
rule := r if { count(deny) == 0; some r in hold }
rule := r if { count(deny) == 0; count(hold) == 0; some r in allow }
